project:
  type: website

website:
  title: "Centre for Household Finance"
  navbar:
    title: false
    logo: "images/logo.svg"
    right:
      - text: Research
        href: research.qmd
      - text: Team
        href: team.qmd
  search: false
  favicon: favicon.png
  page-footer:
    background: dark 
    right: |
      &copy; 2025 Centre for Household Finance.

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">



